### ISSUE TITLE
Allow to mark fields as non-persistent

### ISSUE THREAD

**Issue by bogeeee** [bogeeee/mini-db#2]
Best would be to have an:
`@ persitence({persist: false})
`
decorator.

Tests should also be written for that.
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #2</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @bogeeee</code> (replace <code>20</code> with the amount, and <code>@bogeeee</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by bogeeee** [comment]
/reward 50<details><summary>How to earn this $50.00 reward?</summary><br/>💪 Comment `/try` and start working on solving the issue!
🙌 And when you open the PR, comment `/claim #2` either in the PR description or in a PR's comment
        </details>

**Comment by RubenRuCh** [comment]
Hey @bogeeee, really love the idea of the project! Let's see if we can get some contributions going

/reward 25<details><summary>How to earn this $25.00 reward?</summary><br/>💪 Comment `/try` and start working on solving the issue!
🙌 And when you open the PR, comment `/claim #2` either in the PR description or in a PR's comment
        </details>

**Comment by arugerdev** [comment]
/try<details><summary>Check if you're the only one trying 👇</summary><br/>Perfect! You're the first one to try to solve this issue, go for it! 😉</details>

**Comment by arugerdev** [comment]
The **PR** is **complete**, **ready** to **review**, **all tests have been passed successfully**, sorry for the delay in fixing the mistake I made.

And thanks for the opportunity to contribute your code and try Opire for the first time <3

**Comment by bogeeee** [comment]
@arugerdev: Thx. Hope you had fun with it ! Will make the npm publish soon.
